name: pr

on: [pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run yarn lint
              run: |
                  yarn install
                  cd packages/backend && yarn install
                  cd ../frontend && yarn install
                  cd ../..
                  yarn lint
